name: connect_pharma
description: Connect-Pharma demo
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.2
  image_picker: ^1.2.1
  firebase_storage: ^13.0.5
  uuid: ^4.5.2
  google_maps_flutter: ^2.14.0
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0

flutter:
  uses-material-design: true